<?php
// +----------------------------------------------------------------------
// | [RhaPHP System] Copyright (c) 2017 http://www.rhaphp.com/
// +----------------------------------------------------------------------
// | [RhaPHP] 并不是自由软件,你可免费使用,未经许可不能去掉RhaPHP相关版权
// +----------------------------------------------------------------------
// | Author: Geeson <qimengkeji@vip.qq.com>
// +----------------------------------------------------------------------


namespace app\extension\controller;



use think\Db;
use think\Exception;
use think\facade\Request;
use think\facade\Session;
use think\facade\Url;
use think\Validate;
use PHPExcel;

class Excelfile extends Base
{
    protected $excel_id;
    public $excelTitle;
    public $contentList;



    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function index()
    {
        $keyword = input('keyword');
         if ($keyword) {
            $excel_name[] = ['excel_name', 'like', "%{$keyword}%"];
        }else{
            $excel_name = '';
        }
        $result = Db::name('excel')
            ->where('status=1')
            ->where($excel_name)
            ->order('id','desc')
            ->paginate(10,false,['query' => ['keyword'=>$keyword]]
        );

        $page = $result->render();
        $this->assign('keyword',$keyword);
        $this->assign('count',$result->total());
        $this->assign('data',$result);
        $this->assign('page', $page);
        return view();
    }

    // 详情页面
    public function details(){

    }

    // 删除一条数据
    public function delete(){
        $id = input('post.');
        $excelRes = Db::name('excel')
        ->where($id)
        ->update(
            ['status'=>'-1']
        );
        if ($excelRes) {
            $excel_rowRes = Db::name('excel_row')
            ->where(array('excel_id'=>$id['id']))
            ->update(
                ['status'=>'-1']
            );
            if ($excel_rowRes) {
                ajaxMsg(1,'删除成功!');
            }else{
                ajaxMsg(0,'删除失败!');
            }
        }

    }

 
}
